server.port=8082

# App name
spring.application.name=food-ordering

# Your LOCAL MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/foodorderingdb
spring.datasource.username=root
spring.datasource.password=root1234

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Auto create/update tables
spring.jpa.hibernate.ddl-auto=update

# MySQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Show SQL in console
spring.jpa.show-sql=true

spring.main.allow-circular-references=true